const wordList = [
    { word: "Algorithm", hint: "A step-by-step set of instructions for solving a problem." },
    { word: "Array", hint: "A collection of elements stored at contiguous memory locations." },
    { word: "Recursion", hint: "A function that calls itself." },
    { word: "Loop", hint: "A programming construct that repeats a block of code." },
    { word: "Function", hint: "A reusable block of code that performs a specific task." },
    { word: "Variable", hint: "A named storage for data values." },
    { word: "Class", hint: "A blueprint for creating objects in object-oriented programming." },
    { word: "Inheritance", hint: "A feature of OOP where a class derives from another class." },
    { word: "Polymorphism", hint: "An OOP concept allowing a function to take different forms." },
    { word: "Encapsulation", hint: "Restricting access to data and methods within a class." },
    { word: "Abstraction", hint: "Hiding implementation details and exposing only necessary parts." },
    { word: "Object", hint: "An instance of a class in object-oriented programming." },
    { word: "Compiler", hint: "A program that converts source code into executable code." },
    { word: "Interpreter", hint: "A program that executes code line by line." },
    { word: "Debugging", hint: "The process of finding and fixing errors in code." },
    { word: "Binary", hint: "The fundamental language of computers using 0s and 1s." },
    { word: "Boolean", hint: "A data type that represents true or false values." },
    { word: "DataStructure", hint: "A way of organizing and storing data." },
    { word: "Stack", hint: "A LIFO data structure (Last In, First Out)." },
    { word: "Queue", hint: "A FIFO data structure (First In, First Out)." },
    { word: "LinkedList", hint: "A data structure where elements are linked using pointers." },
    { word: "HashTable", hint: "A data structure that stores key-value pairs for fast retrieval." },
    { word: "Graph", hint: "A data structure consisting of nodes and edges." },
    { word: "Tree", hint: "A hierarchical data structure with nodes and branches." },
    { word: "BinaryTree", hint: "A tree where each node has at most two children." },
    { word: "Sorting", hint: "The process of arranging data in a specific order." },
    { word: "BubbleSort", hint: "A simple sorting algorithm that repeatedly swaps adjacent elements." },
    { word: "QuickSort", hint: "A fast sorting algorithm using divide-and-conquer." },
    { word: "MergeSort", hint: "A sorting algorithm that divides the array and merges sorted parts." },
    { word: "SearchAlgorithm", hint: "A method used to find an element in a dataset." },
    { word: "BinarySearch", hint: "A fast search algorithm that divides a sorted array in half." },
    { word: "Hashing", hint: "A technique for fast data retrieval using a hash function." },
    { word: "Bitwise", hint: "Operations that manipulate bits directly." },
    { word: "Pointer", hint: "A variable that stores the memory address of another variable." },
    { word: "DynamicMemory", hint: "Memory allocation during runtime." },
    { word: "GarbageCollection", hint: "Automatic memory management by reclaiming unused memory." },
    { word: "Multithreading", hint: "Executing multiple threads in a program concurrently." },
    { word: "Concurrency", hint: "Performing multiple tasks simultaneously." },
    { word: "Parallelism", hint: "Executing multiple operations at the exact same time." },
    { word: "Deadlock", hint: "A situation where two or more processes wait indefinitely." },
    { word: "RaceCondition", hint: "A bug caused by the timing of concurrent operations." },
    { word: "Mutex", hint: "A mechanism to prevent simultaneous access to resources." },
    { word: "Semaphore", hint: "A signal used to control access in concurrent processes." },
    { word: "API", hint: "A set of functions that allow software interaction." },
    { word: "REST", hint: "An API architecture style using HTTP methods." },
    { word: "GraphQL", hint: "A query language for APIs with flexible data fetching." },
    { word: "HTTP", hint: "Protocol for communication between web browsers and servers." },
    { word: "HTTPS", hint: "Secure version of HTTP with encryption." },
    { word: "Cookie", hint: "Data stored by websites on a user's browser." },
    { word: "Session", hint: "Temporary data storage for user interactions on a website." },
    { word: "Authentication", hint: "Verifying the identity of a user or system." },
    { word: "OAuth", hint: "An authorization framework for granting access securely." },
    { word: "JWT", hint: "A token-based authentication mechanism." },
    { word: "SQL", hint: "A language used to interact with databases." },
    { word: "NoSQL", hint: "A database system that stores data in flexible formats." },
    { word: "MongoDB", hint: "A NoSQL database that stores data in JSON format." },
    { word: "MySQL", hint: "A widely-used relational database management system." },
    { word: "PostgreSQL", hint: "An advanced, open-source relational database system." },
    { word: "ORM", hint: "An abstraction layer to interact with databases using objects." },
    { word: "Django", hint: "A Python web framework following the MVC pattern." },
    { word: "Flask", hint: "A lightweight Python web framework." },
    { word: "React", hint: "A JavaScript library for building user interfaces." },
    { word: "Angular", hint: "A front-end framework developed by Google." },
    { word: "Vue", hint: "A progressive front-end framework for building web apps." },
    { word: "NodeJS", hint: "A JavaScript runtime for building server-side applications." },
    { word: "ExpressJS", hint: "A minimal framework for building web applications in NodeJS." },
    { word: "Middleware", hint: "Software that connects different applications or services." },
    { word: "Docker", hint: "A platform for developing and deploying applications in containers." },
    { word: "Kubernetes", hint: "A system for managing containerized applications." },
    { word: "CI/CD", hint: "Continuous Integration and Continuous Deployment process." },
    { word: "Git", hint: "A version control system for tracking code changes." },
    { word: "GitHub", hint: "A platform for hosting and collaborating on code." },
    { word: "VersionControl", hint: "A system that tracks changes to files over time." },
    { word: "Testing", hint: "The process of checking if code works as expected." },
    { word: "UnitTest", hint: "Testing individual components of an application." },
    { word: "IntegrationTest", hint: "Testing multiple parts of a system together." },
    { word: "Deployment", hint: "The process of making software available for use." },
    { word: "CloudComputing", hint: "Using remote servers to store and process data." },
    { word: "Serverless", hint: "Cloud computing where the cloud provider manages the infrastructure." },
    { word: "CyberSecurity", hint: "Protecting systems and networks from digital attacks." },
    { word: "Encryption", hint: "The process of converting data into a secure format." },
    { word: "Blockchain", hint: "A decentralized and distributed digital ledger." },
    { word: "MachineLearning", hint: "A type of AI that enables systems to learn from data." },
    { word: "ArtificialIntelligence", hint: "The simulation of human intelligence by machines." },
    { word: "NeuralNetwork", hint: "A system of algorithms modeled after the human brain." },
    { word: "Atom", hint: "Smallest unit of matter." },
    { word: "Molecule", hint: "A group of atoms bonded together." },
    { word: "Element", hint: "A substance made of only one type of atom." },
    { word: "Compound", hint: "Two or more elements chemically bonded." },
    { word: "PeriodicTable", hint: "A chart of elements arranged by atomic number." },
    { word: "CovalentBond", hint: "A chemical bond where atoms share electrons." },
    { word: "IonicBond", hint: "A bond formed by electron transfer between atoms." },
    { word: "Metal", hint: "An element that is a good conductor of electricity." },
    { word: "Nonmetal", hint: "An element that lacks metallic properties." },
    { word: "Metalloid", hint: "An element with properties of metals and nonmetals." },
    { word: "Acid", hint: "A substance with a pH lower than 7." },
    { word: "Base", hint: "A substance with a pH higher than 7." },
    { word: "Neutral", hint: "A solution with a pH of exactly 7." },
    { word: "pHScale", hint: "A scale used to measure acidity or basicity." },
    { word: "Oxidation", hint: "A reaction where a substance loses electrons." },
    { word: "Reduction", hint: "A reaction where a substance gains electrons." },
    { word: "Catalyst", hint: "A substance that speeds up a chemical reaction." },
    { word: "ReactionRate", hint: "The speed at which a chemical reaction occurs." },
    { word: "Endothermic", hint: "A reaction that absorbs heat energy." },
    { word: "Exothermic", hint: "A reaction that releases heat energy." },
    { word: "Solution", hint: "A homogeneous mixture of two or more substances." },
    { word: "Solvent", hint: "The substance that dissolves the solute." },
    { word: "Solute", hint: "The substance dissolved in a solvent." },
    { word: "Precipitate", hint: "An insoluble solid formed from a solution." },
    { word: "Electrolysis", hint: "A chemical reaction caused by electricity." },
    { word: "Alloy", hint: "A mixture of two or more metals." },
    { word: "Radioactive", hint: "An unstable substance that emits radiation." },
    { word: "Isotope", hint: "Atoms of the same element with different neutrons." },
    { word: "NuclearFission", hint: "A reaction where a nucleus splits into smaller parts." },
    { word: "NuclearFusion", hint: "A reaction where atomic nuclei combine to form a heavier nucleus." },
    { word: "Polarity", hint: "A molecule's distribution of electric charge." },
    { word: "Valency", hint: "The combining power of an element." },
    { word: "Hydrocarbon", hint: "A compound made of hydrogen and carbon." },
    { word: "Carbohydrate", hint: "An organic compound made of carbon, hydrogen, and oxygen." },
    { word: "Protein", hint: "A large molecule made of amino acids." },
    { word: "Lipid", hint: "A biomolecule used for energy storage and cell membranes." },
    { word: "Enzyme", hint: "A biological catalyst that speeds up reactions." },
    { word: "Distillation", hint: "A process used to separate liquids based on boiling points." },
    { word: "Fermentation", hint: "A chemical process that produces alcohol or organic acids." },
    { word: "Electronegativity", hint: "An atom's ability to attract electrons." },
    { word: "ActivationEnergy", hint: "The energy needed to start a reaction." },
    { word: "Buffer", hint: "A solution that resists changes in pH." },
    { word: "Titration", hint: "A technique to determine an unknown concentration." },
    { word: "Equilibrium", hint: "A state where reactants and products remain constant." },
    { word: "Sublimation", hint: "A process where a solid turns directly into gas." },
    { word: "Deposition", hint: "A process where a gas turns directly into solid." },
    { word: "Evaporation", hint: "A liquid turning into vapor." },
    { word: "Condensation", hint: "A gas turning into liquid." },
    { word: "BoilingPoint", hint: "The temperature where a liquid becomes gas." },
    { word: "MeltingPoint", hint: "The temperature where a solid becomes liquid." },
    { word: "FreezingPoint", hint: "The temperature where a liquid becomes solid." },
    { word: "SaturatedSolution", hint: "A solution that contains the maximum amount of solute." },
    { word: "UnsaturatedSolution", hint: "A solution that can dissolve more solute." },
    { word: "SupersaturatedSolution", hint: "A solution containing more solute than it should hold." },
    { word: "LeChatelierPrinciple", hint: "A rule describing how equilibrium shifts when disturbed." },
    { word: "CollisionTheory", hint: "A theory stating that atoms must collide to react." },
    { word: "AvogadroNumber", hint: "The number of particles in one mole (6.022×10²³)." },
    { word: "Mole", hint: "A unit measuring amount of substance." },
    { word: "Molarity", hint: "A concentration unit (moles per liter)." },
    { word: "Molality", hint: "A concentration unit (moles per kg of solvent)." },
    { word: "Electrolyte", hint: "A substance that conducts electricity in solution." },
    { word: "NonElectrolyte", hint: "A substance that does not conduct electricity in solution." },
    { word: "Salt", hint: "A compound formed from acid-base reactions." },
    { word: "OxidizingAgent", hint: "A substance that gains electrons in a reaction." },
    { word: "ReducingAgent", hint: "A substance that loses electrons in a reaction." },
    { word: "Hydration", hint: "The process of water molecules surrounding ions." },
    { word: "Corrosion", hint: "The process where metals deteriorate due to oxidation." },
    { word: "HardWater", hint: "Water with high mineral content." },
    { word: "SoftWater", hint: "Water with low mineral content." },
    { word: "Fluorescence", hint: "A substance emitting light when exposed to radiation." },
    { word: "Chromatography", hint: "A technique to separate mixtures based on movement through a medium." },
    { word: "Amphoteric", hint: "A substance that can act as both acid and base." },
    { word: "Hydrolysis", hint: "A reaction involving the breakdown of a compound using water." },
    { word: "Emulsion", hint: "A mixture of two liquids that normally don't mix." },
    { word: "Viscosity", hint: "A measure of a fluid's resistance to flow." },
    { word: "Plasma", hint: "A state of matter where atoms are ionized." },
    { word: "Crystallization", hint: "A process of forming solid crystals from a solution." },
    { word: "Polymer", hint: "A large molecule made of repeating units." },
    { word: "Monomer", hint: "A small unit that joins to form polymers." },
    { word: "Alkene", hint: "A hydrocarbon with at least one double bond." },
    { word: "Alkyne", hint: "A hydrocarbon with at least one triple bond." },
    { word: "Benzene", hint: "A ring-shaped hydrocarbon with alternating double bonds." },
    { word: "Ester", hint: "An organic compound formed from an acid and alcohol." },
    { word: "Ketone", hint: "An organic compound with a carbonyl group." },
    { word: "Aldehyde", hint: "An organic compound with a carbonyl group at the end." },
    { word: "Carboxyl", hint: "A functional group (-COOH) found in acids." },
    { word: "Isomer", hint: "Compounds with the same formula but different structures." },
    { word: "Cell", hint: "The basic unit of life." },
    { word: "Nucleus", hint: "The control center of a cell, contains DNA." },
    { word: "Mitochondria", hint: "The powerhouse of the cell, produces energy." },
    { word: "Ribosome", hint: "Organelle that synthesizes proteins." },
    { word: "Chloroplast", hint: "Organelle in plant cells that performs photosynthesis." },
    { word: "Photosynthesis", hint: "Process by which plants make food using sunlight." },
    { word: "Respiration", hint: "Process of breaking down glucose for energy." },
    { word: "DNA", hint: "Genetic material that carries instructions for life." },
    { word: "RNA", hint: "Molecule that helps in protein synthesis." },
    { word: "Gene", hint: "A segment of DNA that codes for a protein." },
    { word: "Chromosome", hint: "A structure made of DNA and proteins." },
    { word: "Mutation", hint: "A change in the DNA sequence." },
    { word: "Enzyme", hint: "A protein that speeds up chemical reactions in cells." },
    { word: "Protein", hint: "A macromolecule essential for growth and repair." },
    { word: "Lipids", hint: "Fats and oils used for long-term energy storage." },
    { word: "Carbohydrate", hint: "Macromolecule that provides quick energy." },
    { word: "Eukaryote", hint: "A cell with a nucleus and membrane-bound organelles." },
    { word: "Prokaryote", hint: "A cell without a nucleus." },
    { word: "Osmosis", hint: "The movement of water across a membrane." },
    { word: "Diffusion", hint: "The movement of molecules from high to low concentration." },
    { word: "ActiveTransport", hint: "Movement of molecules against a concentration gradient, requires energy." },
    { word: "Homeostasis", hint: "The maintenance of a stable internal environment." },
    { word: "Hormone", hint: "A chemical messenger in the body." },
    { word: "Neuron", hint: "A nerve cell that transmits signals." },
    { word: "Synapse", hint: "A gap between nerve cells where communication occurs." },
    { word: "Hemoglobin", hint: "Protein in red blood cells that carries oxygen." },
    { word: "Antibody", hint: "A protein that helps fight infections." },
    { word: "Vaccine", hint: "A substance that stimulates the immune system against disease." },
    { word: "Virus", hint: "A tiny infectious agent that requires a host to reproduce." },
    { word: "Bacteria", hint: "Single-celled microorganisms, some beneficial, some harmful." },
    { word: "Fungus", hint: "An organism like mold or mushrooms." },
    { word: "Protist", hint: "A diverse group of mostly single-celled organisms." },
    { word: "Parasite", hint: "An organism that lives on or inside another and harms it." },
    { word: "Ecology", hint: "The study of how organisms interact with their environment." },
    { word: "Ecosystem", hint: "A community of organisms and their environment." },
    { word: "FoodChain", hint: "A sequence showing energy flow in an ecosystem." },
    { word: "Producer", hint: "An organism that makes its own food, like plants." },
    { word: "Consumer", hint: "An organism that eats other organisms." },
    { word: "Decomposer", hint: "An organism that breaks down dead material." },
    { word: "Biodiversity", hint: "The variety of life in an ecosystem." },
    { word: "Adaptation", hint: "A trait that helps an organism survive." },
    { word: "Evolution", hint: "The process of change in species over time." },
    { word: "NaturalSelection", hint: "Survival of the fittest; drives evolution." },
    { word: "Speciation", hint: "The formation of new species over time." },
    { word: "Extinction", hint: "The disappearance of a species." },
    { word: "Genetics", hint: "The study of heredity and variation in organisms." },
    { word: "Heredity", hint: "The passing of traits from parents to offspring." },
    { word: "DominantTrait", hint: "A trait that is expressed even if only one allele is present." },
    { word: "RecessiveTrait", hint: "A trait that is only expressed when two copies are present." },
    { word: "Genotype", hint: "The genetic makeup of an organism." },
    { word: "Phenotype", hint: "The physical expression of a trait." },
    { word: "PunnettSquare", hint: "A tool used to predict genetic crosses." },
    { word: "Mitosis", hint: "Cell division that produces two identical cells." },
    { word: "Meiosis", hint: "Cell division that produces reproductive cells." },
    { word: "Zygote", hint: "The first cell of a new organism after fertilization." },
    { word: "Embryo", hint: "An early stage of development in multicellular organisms." },
    { word: "Fetus", hint: "A developing human after eight weeks of pregnancy." },
    { word: "Autotroph", hint: "An organism that makes its own food." },
    { word: "Heterotroph", hint: "An organism that consumes other organisms for food." },
    { word: "Vertebrate", hint: "An animal with a backbone." },
    { word: "Invertebrate", hint: "An animal without a backbone." },
    { word: "Amphibian", hint: "A cold-blooded vertebrate that lives both in water and on land." },
    { word: "Reptile", hint: "A cold-blooded vertebrate with scales." },
    { word: "Mammal", hint: "A warm-blooded animal with hair and mammary glands." },
    { word: "Bird", hint: "A warm-blooded vertebrate with feathers and wings." },
    { word: "Fish", hint: "A cold-blooded vertebrate that lives in water and has gills." },
    { word: "CirculatorySystem", hint: "The system that transports blood throughout the body." },
    { word: "RespiratorySystem", hint: "The system that enables breathing." },
    { word: "DigestiveSystem", hint: "The system that processes food into energy." },
    { word: "NervousSystem", hint: "The system that controls body functions and responses." },
    { word: "EndocrineSystem", hint: "The system that produces hormones." },
    { word: "ExcretorySystem", hint: "The system that removes waste from the body." },
    { word: "SkeletalSystem", hint: "The framework of bones that supports the body." },
    { word: "MuscularSystem", hint: "The system that allows movement." },
    { word: "ImmuneSystem", hint: "The system that protects the body from infections." },
    { word: "ReproductiveSystem", hint: "The system responsible for producing offspring." },
    { word: "StemCell", hint: "A cell with the potential to develop into many different types of cells." },
    { word: "Hormone", hint: "A chemical messenger in the body." },
    { word: "Neurotransmitter", hint: "A chemical that transmits signals in the nervous system." },
    { word: "Virus", hint: "A tiny infectious agent that requires a host to reproduce." },
    { word: "Bacteria", hint: "Single-celled microorganisms, some beneficial, some harmful." },
    { word: "Fungi", hint: "An organism like mold or mushrooms." },
    { word: "Antibiotic", hint: "A medicine that kills bacteria." },
    { word: "Vaccine", hint: "A substance that stimulates the immune system against disease." },
    { word: "Mutation", hint: "A change in the DNA sequence." },
    { word: "Decomposition", hint: "The process of breaking down organic matter." },
    { word: "Force", hint: "A push or pull acting on an object." },
    { word: "Gravity", hint: "The force that pulls objects toward the center of the Earth." },
    { word: "Acceleration", hint: "The rate of change of velocity." },
    { word: "Velocity", hint: "Speed in a given direction." },
    { word: "Inertia", hint: "The tendency of an object to resist changes in motion." },
    { word: "Momentum", hint: "Mass times velocity; a measure of motion." },
    { word: "Newton", hint: "Scientist known for the three laws of motion." },
    { word: "Friction", hint: "A force that opposes motion between two surfaces." },
    { word: "Mass", hint: "The amount of matter in an object." },
    { word: "Weight", hint: "The force of gravity acting on an object's mass." },
    { word: "Energy", hint: "The capacity to do work." },
    { word: "Work", hint: "Force applied over a distance." },
    { word: "Power", hint: "The rate at which work is done." },
    { word: "KineticEnergy", hint: "Energy of a moving object." },
    { word: "PotentialEnergy", hint: "Stored energy based on position." },
    { word: "Thermodynamics", hint: "The study of heat and energy transfer." },
    { word: "Heat", hint: "Thermal energy transferred from one body to another." },
    { word: "Temperature", hint: "A measure of the average kinetic energy of particles." },
    { word: "Conduction", hint: "Heat transfer through direct contact." },
    { word: "Convection", hint: "Heat transfer through fluid movement." },
    { word: "Radiation", hint: "Heat transfer through electromagnetic waves." },
    { word: "Entropy", hint: "A measure of disorder in a system." },
    { word: "Wave", hint: "A disturbance that transfers energy." },
    { word: "Frequency", hint: "The number of waves passing a point per second." },
    { word: "Wavelength", hint: "The distance between two wave peaks." },
    { word: "Amplitude", hint: "The height of a wave; related to energy." },
    { word: "Sound", hint: "A type of wave that travels through air and other mediums." },
    { word: "Echo", hint: "A sound wave that reflects back." },
    { word: "DopplerEffect", hint: "Change in frequency due to motion of a source." },
    { word: "Electromagnetism", hint: "The study of electric and magnetic fields." },
    { word: "Electricity", hint: "The flow of electric charge." },
    { word: "Voltage", hint: "The potential difference in an electrical circuit." },
    { word: "Current", hint: "The flow of electric charge in a circuit." },
    { word: "Resistance", hint: "Opposition to the flow of electric current." },
    { word: "Ohm", hint: "Unit of electrical resistance." },
    { word: "Capacitor", hint: "A device that stores electrical energy." },
    { word: "Inductor", hint: "A device that opposes changes in current." },
    { word: "Magnetism", hint: "A force of attraction or repulsion due to a magnetic field." },
    { word: "MagneticField", hint: "The area around a magnet where magnetic forces act." },
    { word: "Electromagnet", hint: "A magnet created by electric current." },
    { word: "Transformer", hint: "A device that changes voltage levels." },
    { word: "Photon", hint: "A particle of light." },
    { word: "Refraction", hint: "The bending of light as it passes through a medium." },
    { word: "Reflection", hint: "The bouncing back of light from a surface." },
    { word: "Lens", hint: "A transparent object that bends light rays." },
    { word: "Prism", hint: "A transparent object that splits light into colors." },
    { word: "Optics", hint: "The study of light behavior." },
    { word: "Infrared", hint: "Light waves that are longer than visible light but shorter than microwaves." },
    { word: "Ultraviolet", hint: "Light waves with higher energy than visible light." },
    { word: "XRay", hint: "High-energy waves used in medical imaging." },
    { word: "GammaRay", hint: "The highest energy electromagnetic waves." },
    { word: "Nuclear", hint: "Relating to the nucleus of an atom." },
    { word: "Fission", hint: "Splitting of an atomic nucleus to release energy." },
    { word: "Fusion", hint: "The process of combining atomic nuclei to release energy." },
    { word: "Radioactivity", hint: "The emission of particles from an unstable nucleus." },
    { word: "HalfLife", hint: "The time required for half of a radioactive substance to decay." },
    { word: "Quantum", hint: "The smallest possible discrete unit of energy." },
    { word: "QuantumMechanics", hint: "The study of physics at atomic and subatomic levels." },
    { word: "Schrodinger", hint: "Physicist known for his cat thought experiment." },
    { word: "Superposition", hint: "The ability of quantum particles to exist in multiple states." },
    { word: "Entanglement", hint: "A quantum property where particles remain connected." },
    { word: "Relativity", hint: "Einstein's theory about space, time, and gravity." },
    { word: "TimeDilation", hint: "The effect of time slowing down due to high speed or gravity." },
    { word: "BlackHole", hint: "A region in space where gravity is so strong that not even light can escape." },
    { word: "Singularity", hint: "A point in space with infinite density." },
    { word: "BigBang", hint: "The event that started the universe." },
    { word: "DarkMatter", hint: "Invisible matter that affects gravity in the universe." },
    { word: "DarkEnergy", hint: "A mysterious force causing the universe to expand faster." },
    { word: "StringTheory", hint: "A theoretical framework in which particles are one-dimensional strings." },
    { word: "Neutrino", hint: "A nearly massless subatomic particle that rarely interacts with matter." },
    { word: "HiggsBoson", hint: "A particle that gives mass to other particles." },
    { word: "Superconductor", hint: "A material that conducts electricity with zero resistance." },
    { word: "Entropy", hint: "A measure of disorder in a system." },
    { word: "Interference", hint: "The interaction of overlapping waves." },
    { word: "Diffraction", hint: "The bending of waves around obstacles." },
    { word: "DopplerEffect", hint: "The change in frequency of a wave as the source moves." },
    { word: "Turbulence", hint: "Irregular or chaotic fluid motion." },
    { word: "CentripetalForce", hint: "The force that keeps an object moving in a circular path." },
    { word: "EscapeVelocity", hint: "The speed needed to break free from a gravitational field." },
    { word: "TerminalVelocity", hint: "The maximum speed an object can reach while falling." },
    { word: "Projectile", hint: "An object moving through space under the influence of gravity." },
    { word: "HarmonicMotion", hint: "Motion that repeats in a regular cycle, like a pendulum." },
    { word: "Torque", hint: "A force that causes rotation." },
    { word: "Pendulum", hint: "A weight suspended from a pivot that swings back and forth." },
    { word: "Resonance", hint: "The amplification of vibrations at a natural frequency." },
    { word: "Equilibrium", hint: "A state where forces are balanced." }
];