const wordList = [
    { word: "variable", hint: "A named storage for data in programming." },
    { word: "function", hint: "A reusable block of code that performs a task." },
    { word: "array", hint: "A data structure that stores multiple values." },
    { word: "object", hint: "A collection of key-value pairs in programming." },
    { word: "class", hint: "A blueprint for creating objects in OOP." },
    { word: "method", hint: "A function associated with an object or class." },
    { word: "loop", hint: "A control structure that repeats a block of code." },
    { word: "recursion", hint: "A function that calls itself." },
    { word: "compiler", hint: "A program that translates source code into machine code." },
    { word: "interpreter", hint: "A program that executes code line by line." },
    { word: "syntax", hint: "The rules defining a valid code structure." },
    { word: "debugging", hint: "The process of finding and fixing errors in code." },
    { word: "framework", hint: "A collection of pre-written code to simplify development." },
    { word: "library", hint: "A collection of reusable functions and modules." },
    { word: "database", hint: "An organized collection of structured data." },
    { word: "query", hint: "A request for data from a database." },
    { word: "frontend", hint: "The part of a website users interact with." },
    { word: "backend", hint: "The server-side logic of an application." },
    { word: "fullstack", hint: "A developer skilled in both frontend and backend." },
    { word: "json", hint: "A lightweight format for data exchange." },
    { word: "api", hint: "A set of functions allowing applications to communicate." },
    { word: "authentication", hint: "The process of verifying user identity." },
    { word: "authorization", hint: "The process of granting user permissions." },
    { word: "encryption", hint: "The process of securing data by encoding it." },
    { word: "hashing", hint: "A process that converts data into a fixed-length string." },
    { word: "docker", hint: "A platform for containerizing applications." },
    { word: "virtualization", hint: "Creating virtual versions of physical resources." },
    { word: "cloud", hint: "Remote servers storing and processing data." },
    { word: "deployment", hint: "Releasing software to a live environment." },
    { word: "git", hint: "A version control system for tracking changes in code." },
    { word: "github", hint: "A platform for hosting and collaborating on code." },
    { word: "branch", hint: "A parallel version of a repository in Git." },
    { word: "merge", hint: "Combining branches in version control." },
    { word: "commit", hint: "A saved change in a Git repository." },
    { word: "repository", hint: "A storage location for project files in Git." },
    { word: "caching", hint: "Storing data temporarily for faster access." },
    { word: "server", hint: "A computer that provides services to other computers." },
    { word: "client", hint: "A device or program that accesses a server." },
    { word: "middleware", hint: "Software that connects different applications." },
    { word: "socket", hint: "A communication endpoint for network connections." },
    { word: "port", hint: "A communication endpoint identified by a number." },
    { word: "protocol", hint: "A set of rules for data exchange in networks." },
    { word: "firewall", hint: "A security system that monitors network traffic." },
    { word: "cookie", hint: "A small piece of data stored by a browser." },
    { word: "session", hint: "A period of interaction between a user and a system." },
    { word: "token", hint: "A security key used for authentication." },
    { word: "oauth", hint: "An authentication framework for secure login." },
    { word: "jwt", hint: "A compact format for securely transmitting information." },
    { word: "thread", hint: "The smallest unit of execution in a program." },
    { word: "process", hint: "An instance of a running program." },
    { word: "parallelism", hint: "Executing multiple tasks simultaneously." },
    { word: "asynchronous", hint: "Execution that allows tasks to run independently." },
    { word: "synchronous", hint: "Execution that follows a sequential order." },
    { word: "callback", hint: "A function passed as an argument to another function." },
    { word: "promise", hint: "An object representing a future value or event." },
    { word: "closure", hint: "A function with access to its outer scope." },
    { word: "hoisting", hint: "JavaScript’s default behavior of moving declarations to the top." },
    { word: "event", hint: "An action that triggers a response in programming." },
    { word: "listener", hint: "A function that waits for an event to occur." },
    { word: "dom", hint: "A programming interface for web pages." },
    { word: "component", hint: "A reusable UI element in frameworks like React." },
    { word: "jsx", hint: "A syntax extension for writing React components." },
    { word: "hook", hint: "A function in React that manages state and effects." },
    { word: "state", hint: "A JavaScript object that holds component data." },
    { word: "context", hint: "A way to pass data through a component tree." },
    { word: "redux", hint: "A state management library for JavaScript apps." },
    { word: "typescript", hint: "A superset of JavaScript with static typing." },
    { word: "python", hint: "A high-level programming language known for simplicity." },
    { word: "java", hint: "A widely used object-oriented programming language." },
    { word: "csharp", hint: "A language used mainly for Windows applications." },
    { word: "swift", hint: "A programming language for iOS development." },
    { word: "kotlin", hint: "A language used for Android development." },
    { word: "golang", hint: "A language known for concurrency and performance." },
    { word: "ruby", hint: "A dynamic programming language often used in web development." },
    { word: "sql", hint: "A language for managing relational databases." },
    { word: "nosql", hint: "A database format that doesn’t use structured tables." },
    { word: "mongodb", hint: "A NoSQL database that stores data in JSON-like format." },
    { word: "postgresql", hint: "An advanced open-source relational database system." },
    { word: "orm", hint: "A technique for interacting with databases using objects." },
    { word: "indexing", hint: "A technique to speed up database queries." },
    { word: "pagination", hint: "Dividing content into multiple pages." },
    { word: "cdn", hint: "A network of servers to deliver content faster." },
    { word: "websocket", hint: "A communication protocol for real-time data transfer." },
    { word: "graphql", hint: "A query language for APIs." },
    { word: "restful", hint: "An API design principle using HTTP methods." },
    { word: "microservices", hint: "An architecture style for building scalable applications." },
    { word: "container", hint: "A lightweight, portable environment for running applications." },
    { word: "testing", hint: "The process of evaluating software for errors." },
    { word: "unit", hint: "A small, testable part of an application." },
    { word: "mocking", hint: "Simulating components in testing." },
    { word: "atom", hint: "The smallest unit of matter." },
    { word: "molecule", hint: "Two or more atoms bonded together." },
    { word: "element", hint: "A pure substance consisting of one type of atom." },
    { word: "compound", hint: "A substance formed by two or more elements chemically combined." },
    { word: "reaction", hint: "A process where substances transform into new substances." },
    { word: "catalyst", hint: "A substance that speeds up a chemical reaction." },
    { word: "oxidation", hint: "A reaction involving the loss of electrons." },
    { word: "reduction", hint: "A reaction involving the gain of electrons." },
    { word: "acid", hint: "A substance that donates protons in a reaction." },
    { word: "base", hint: "A substance that accepts protons in a reaction." },
    { word: "salt", hint: "A compound formed from an acid and a base." },
    { word: "pH", hint: "A scale that measures acidity or basicity." },
    { word: "buffer", hint: "A solution that resists pH change." },
    { word: "titration", hint: "A technique to determine concentration of a solution." },
    { word: "isotope", hint: "Atoms of the same element with different masses." },
    { word: "ion", hint: "An atom or molecule with a charge." },
    { word: "anion", hint: "A negatively charged ion." },
    { word: "cation", hint: "A positively charged ion." },
    { word: "electrolysis", hint: "A process that uses electricity to cause a reaction." },
    { word: "periodic", hint: "Refers to the arrangement of elements in a table." },
    { word: "alloy", hint: "A mixture of metals." },
    { word: "bond", hint: "The force holding atoms together in a molecule." },
    { word: "covalent", hint: "A type of bond where atoms share electrons." },
    { word: "ionic", hint: "A type of bond formed by charged particles." },
    { word: "metal", hint: "An element that conducts electricity and heat." },
    { word: "nonmetal", hint: "An element that lacks metallic properties." },
    { word: "metalloid", hint: "An element with properties of both metals and nonmetals." },
    { word: "radioactive", hint: "Describes an unstable element that emits radiation." },
    { word: "nuclear", hint: "Relating to the nucleus of an atom." },
    { word: "fusion", hint: "A process where atoms combine to form a heavier nucleus." },
    { word: "fission", hint: "A process where an atomic nucleus splits into smaller parts." },
    { word: "enthalpy", hint: "A measure of heat content in a system." },
    { word: "entropy", hint: "A measure of disorder in a system." },
    { word: "exothermic", hint: "A reaction that releases heat." },
    { word: "endothermic", hint: "A reaction that absorbs heat." },
    { word: "kinetics", hint: "The study of reaction rates." },
    { word: "equilibrium", hint: "A state where forward and reverse reactions occur at equal rates." },
    { word: "solubility", hint: "The ability of a substance to dissolve in a solvent." },
    { word: "solvent", hint: "A substance that dissolves another substance." },
    { word: "solute", hint: "A substance that gets dissolved." },
    { word: "solution", hint: "A homogeneous mixture of solute and solvent." },
    { word: "precipitate", hint: "A solid formed in a chemical reaction." },
    { word: "distillation", hint: "A process of separating substances by boiling." },
    { word: "filtration", hint: "A method for separating solids from liquids." },
    { word: "chromatography", hint: "A technique used to separate mixtures." },
    { word: "adsorption", hint: "The adhesion of molecules onto a surface." },
    { word: "absorption", hint: "The process of taking in a substance." },
    { word: "hydrate", hint: "A compound containing water molecules." },
    { word: "polymer", hint: "A large molecule made of repeating units." },
    { word: "monomer", hint: "A single unit that forms polymers." },
    { word: "alkane", hint: "A hydrocarbon with single bonds." },
    { word: "alkene", hint: "A hydrocarbon with at least one double bond." },
    { word: "alkyne", hint: "A hydrocarbon with at least one triple bond." },
    { word: "aromatic", hint: "A compound with a benzene ring." },
    { word: "ester", hint: "An organic compound with a fruity smell." },
    { word: "ether", hint: "An organic compound with an oxygen atom between carbons." },
    { word: "amine", hint: "An organic compound containing nitrogen." },
    { word: "ketone", hint: "An organic compound with a carbonyl group." },
    { word: "aldehyde", hint: "An organic compound with a carbonyl at the end of a chain." },
    { word: "carboxyl", hint: "A functional group found in acids." },
    { word: "saponification", hint: "The process of making soap." },
    { word: "stoichiometry", hint: "The calculation of reactants and products in chemistry." },
    { word: "limiting", hint: "The reactant that determines the amount of product formed." },
    { word: "yield", hint: "The amount of product obtained in a reaction." },
    { word: "concentration", hint: "The amount of solute in a solution." },
    { word: "collision", hint: "Theory explaining how molecules react." },
    { word: "activation", hint: "The minimum energy needed for a reaction to occur." },
    { word: "valence", hint: "The number of electrons an atom can share or transfer." },
    { word: "octet", hint: "A stable arrangement of eight electrons in the outer shell." },
    { word: "orbital", hint: "A region in an atom where electrons are likely found." },
    { word: "hybridization", hint: "Mixing of atomic orbitals to form new orbitals." },
    { word: "dipole", hint: "A molecule with a positive and negative end." },
    { word: "polarity", hint: "A measure of charge separation in a molecule." },
    { word: "electronegativity", hint: "The ability of an atom to attract electrons." },
    { word: "ionization", hint: "The process of removing an electron from an atom." },
    { word: "mass", hint: "The amount of matter in an object." },
    { word: "density", hint: "Mass per unit volume of a substance." },
    { word: "pressure", hint: "Force exerted per unit area." },
    { word: "volume", hint: "The amount of space occupied by a substance." },
    { word: "mole", hint: "A unit representing 6.022 x 10^23 particles." },
    { word: "gas", hint: "A state of matter with no fixed shape or volume." },
    { word: "liquid", hint: "A state of matter with a definite volume but no fixed shape." },
    { word: "solid", hint: "A state of matter with definite shape and volume." },
    { word: "plasma", hint: "A high-energy state of matter." },
    { word: "boiling", hint: "The process of a liquid turning into a gas." },
    { word: "melting", hint: "The process of a solid turning into a liquid." },
    { word: "freezing", hint: "The process of a liquid turning into a solid." },
    { word: "sublimation", hint: "A process where a solid turns into gas directly." },
    { word: "allotrope", hint: "Different structural forms of the same element." },
    { word: "cell", hint: "The basic unit of life." },
    { word: "nucleus", hint: "The control center of a eukaryotic cell." },
    { word: "membrane", hint: "A protective barrier surrounding the cell." },
    { word: "mitosis", hint: "A type of cell division resulting in two identical cells." },
    { word: "meiosis", hint: "A type of cell division that produces gametes." },
    { word: "chromosome", hint: "A structure containing genetic information." },
    { word: "gene", hint: "A unit of heredity made of DNA." },
    { word: "allele", hint: "Different versions of a gene." },
    { word: "mutation", hint: "A change in the DNA sequence." },
    { word: "ribosome", hint: "The site of protein synthesis in a cell." },
    { word: "cytoplasm", hint: "The gel-like substance inside a cell." },
    { word: "mitochondria", hint: "The powerhouse of the cell." },
    { word: "chloroplast", hint: "The site of photosynthesis in plant cells." },
    { word: "photosynthesis", hint: "The process by which plants make food." },
    { word: "respiration", hint: "The process of converting glucose into energy." },
    { word: "enzyme", hint: "A protein that speeds up chemical reactions." },
    { word: "hormone", hint: "A signaling molecule in the body." },
    { word: "homeostasis", hint: "The maintenance of a stable internal environment." },
    { word: "osmosis", hint: "The movement of water across a membrane." },
    { word: "diffusion", hint: "The passive movement of molecules from high to low concentration." },
    { word: "antibody", hint: "A protein that fights infections." },
    { word: "antigen", hint: "A substance that triggers an immune response." },
    { word: "vaccine", hint: "A substance that stimulates an immune response." },
    { word: "bacteria", hint: "Single-celled microorganisms without a nucleus." },
    { word: "virus", hint: "A non-living infectious agent with genetic material." },
    { word: "fungus", hint: "A kingdom of organisms including mushrooms and molds." },
    { word: "protist", hint: "A diverse group of eukaryotic microorganisms." },
    { word: "ecology", hint: "The study of interactions between organisms and their environment." },
    { word: "biome", hint: "A large ecosystem with distinct climate and organisms." },
    { word: "population", hint: "A group of the same species living in an area." },
    { word: "community", hint: "Different species living together in an area." },
    { word: "ecosystem", hint: "A community of organisms and their environment." },
    { word: "biosphere", hint: "The global ecological system of all living things." },
    { word: "predator", hint: "An organism that hunts other organisms for food." },
    { word: "prey", hint: "An organism that is hunted for food." },
    { word: "producer", hint: "An organism that makes its own food." },
    { word: "consumer", hint: "An organism that eats other organisms." },
    { word: "decomposer", hint: "An organism that breaks down dead matter." },
    { word: "autotroph", hint: "An organism that produces its own food." },
    { word: "heterotroph", hint: "An organism that gets energy from other sources." },
    { word: "adaptation", hint: "A trait that helps an organism survive." },
    { word: "evolution", hint: "The process of change in species over time." },
    { word: "naturalselection", hint: "The process where traits become more common over generations." },
    { word: "extinction", hint: "The disappearance of a species." },
    { word: "taxonomy", hint: "The classification of living organisms." },
    { word: "kingdom", hint: "A broad classification level of life." },
    { word: "phylum", hint: "A major classification level below kingdom." },
    { word: "class", hint: "A classification rank below phylum." },
    { word: "order", hint: "A classification rank below class." },
    { word: "family", hint: "A classification rank below order." },
    { word: "genus", hint: "A classification rank below family." },
    { word: "species", hint: "The most specific classification rank." },
    { word: "binomial", hint: "A two-part naming system for species." },
    { word: "nervous", hint: "The system that controls the body and senses." },
    { word: "brain", hint: "The organ that controls thoughts and actions." },
    { word: "spinalcord", hint: "The structure that connects the brain to the body." },
    { word: "neuron", hint: "A nerve cell that transmits signals." },
    { word: "synapse", hint: "The gap between neurons where signals pass." },
    { word: "reflex", hint: "An automatic response to a stimulus." },
    { word: "hormone", hint: "A chemical messenger in the body." },
    { word: "digestive", hint: "The system that breaks down food for energy." },
    { word: "stomach", hint: "An organ that digests food with acid." },
    { word: "intestine", hint: "The organ where most nutrient absorption occurs." },
    { word: "liver", hint: "An organ that detoxifies and produces bile." },
    { word: "kidney", hint: "An organ that filters waste from blood." },
    { word: "lung", hint: "An organ that helps in breathing." },
    { word: "alveoli", hint: "Tiny air sacs in the lungs for gas exchange." },
    { word: "circulatory", hint: "The system that transports blood." },
    { word: "heart", hint: "The organ that pumps blood." },
    { word: "artery", hint: "A blood vessel that carries blood away from the heart." },
    { word: "vein", hint: "A blood vessel that carries blood back to the heart." },
    { word: "capillary", hint: "A tiny blood vessel for nutrient exchange." },
    { word: "redbloodcell", hint: "A cell that carries oxygen in the blood." },
    { word: "whitebloodcell", hint: "A cell that helps fight infections." },
    { word: "platelet", hint: "A cell fragment that helps clot blood." },
    { word: "skeletal", hint: "The system that supports and protects the body." },
    { word: "muscle", hint: "Tissue that allows movement." },
    { word: "tendon", hint: "A tissue that connects muscle to bone." },
    { word: "ligament", hint: "A tissue that connects bones together." },
    { word: "cartilage", hint: "A flexible tissue in joints and the nose." },
    { word: "reproductive", hint: "The system responsible for producing offspring." },
    { word: "sperm", hint: "The male reproductive cell." },
    { word: "egg", hint: "The female reproductive cell." },
    { word: "fertilization", hint: "The union of sperm and egg." },
    { word: "embryo", hint: "An early stage of development in animals." },
    { word: "placenta", hint: "An organ that nourishes a developing fetus." },
    { word: "hormone", hint: "A chemical that regulates body functions." },
    { word: "metabolism", hint: "The process of converting food into energy." },
    { word: "protein", hint: "A macromolecule important for structure and function." },
    { word: "lipid", hint: "A type of fat molecule." },
    { word: "carbohydrate", hint: "A source of energy made of sugars." },
    { word: "nucleotide", hint: "The building block of DNA and RNA." },
    { word: "motion", hint: "The change in position of an object over time." },
    { word: "force", hint: "A push or pull acting on an object." },
    { word: "energy", hint: "The ability to do work." },
    { word: "work", hint: "Force applied over a distance." },
    { word: "power", hint: "The rate at which work is done." },
    { word: "velocity", hint: "Speed with a direction." },
    { word: "acceleration", hint: "The rate of change of velocity." },
    { word: "gravity", hint: "A force that pulls objects toward the center of the Earth." },
    { word: "friction", hint: "A force that opposes motion between two surfaces." },
    { word: "momentum", hint: "The product of mass and velocity." },
    { word: "inertia", hint: "The tendency of an object to resist a change in motion." },
    { word: "torque", hint: "A force that causes rotation." },
    { word: "mass", hint: "The amount of matter in an object." },
    { word: "weight", hint: "The force exerted by gravity on an object." },
    { word: "density", hint: "Mass per unit volume of a substance." },
    { word: "pressure", hint: "Force per unit area." },
    { word: "temperature", hint: "A measure of the average kinetic energy of particles." },
    { word: "heat", hint: "Thermal energy transfer between objects." },
    { word: "thermodynamics", hint: "The study of heat and energy transfer." },
    { word: "entropy", hint: "A measure of disorder in a system." },
    { word: "conduction", hint: "Heat transfer through direct contact." },
    { word: "convection", hint: "Heat transfer through fluid movement." },
    { word: "radiation", hint: "Heat transfer through electromagnetic waves." },
    { word: "wave", hint: "A disturbance that transfers energy." },
    { word: "frequency", hint: "The number of wave cycles per second." },
    { word: "wavelength", hint: "The distance between two wave crests or troughs." },
    { word: "amplitude", hint: "The height of a wave from its equilibrium position." },
    { word: "reflection", hint: "The bouncing of light or sound waves off a surface." },
    { word: "refraction", hint: "The bending of light as it passes through different mediums." },
    { word: "diffraction", hint: "The spreading of waves when they pass through an opening." },
    { word: "interference", hint: "The combination of two or more waves." },
    { word: "optics", hint: "The study of light behavior." },
    { word: "lens", hint: "A transparent object that refracts light." },
    { word: "mirror", hint: "A reflective surface that bounces back light." },
    { word: "photon", hint: "A particle of light." },
    { word: "electricity", hint: "The flow of electric charge." },
    { word: "current", hint: "The flow of electric charge per unit time." },
    { word: "voltage", hint: "The potential difference that causes current flow." },
    { word: "resistance", hint: "A material's opposition to current flow." },
    { word: "ohm", hint: "The unit of electrical resistance." },
    { word: "circuit", hint: "A closed loop through which current flows." },
    { word: "battery", hint: "A device that stores and provides electrical energy." },
    { word: "conductor", hint: "A material that allows electricity to flow easily." },
    { word: "insulator", hint: "A material that resists the flow of electricity." },
    { word: "magnet", hint: "An object that produces a magnetic field." },
    { word: "magnetism", hint: "The force exerted by magnets." },
    { word: "electromagnet", hint: "A coil of wire that acts as a magnet when current flows." },
    { word: "induction", hint: "The process of generating voltage by changing a magnetic field." },
    { word: "capacitor", hint: "A device that stores electrical energy." },
    { word: "transformer", hint: "A device that changes the voltage of electricity." },
    { word: "generator", hint: "A device that converts mechanical energy into electricity." },
    { word: "nuclear", hint: "Energy stored in the nucleus of an atom." },
    { word: "fusion", hint: "The process of combining atomic nuclei to release energy." },
    { word: "fission", hint: "The splitting of atomic nuclei to release energy." },
    { word: "atom", hint: "The smallest unit of matter." },
    { word: "proton", hint: "A positively charged particle in an atom." },
    { word: "neutron", hint: "A neutrally charged particle in an atom." },
    { word: "electron", hint: "A negatively charged particle orbiting an atom." },
    { word: "isotope", hint: "Atoms of the same element with different neutron numbers." },
    { word: "quantum", hint: "The smallest possible amount of a physical quantity." },
    { word: "photon", hint: "A particle of electromagnetic radiation." },
    { word: "spin", hint: "A quantum property of particles." },
    { word: "superposition", hint: "The principle that a system can exist in multiple states." },
    { word: "entanglement", hint: "A quantum phenomenon linking particles over distances." },
    { word: "relativity", hint: "Einstein's theory about space, time, and gravity." },
    { word: "gravity", hint: "A force that attracts objects with mass toward each other." },
    { word: "blackhole", hint: "A region in space with immense gravitational pull." },
    { word: "wormhole", hint: "A hypothetical tunnel in spacetime." },
    { word: "space", hint: "The vast expanse beyond Earth's atmosphere." },
    { word: "time", hint: "A dimension in which events occur sequentially." },
    { word: "momentum", hint: "The product of an object's mass and velocity." },
    { word: "collision", hint: "An event where two objects hit each other." },
    { word: "pendulum", hint: "A weight swinging back and forth under gravity." },
    { word: "resonance", hint: "When an object vibrates at its natural frequency." },
    { word: "fluid", hint: "A substance that flows, like liquids and gases." },
    { word: "buoyancy", hint: "The force that allows objects to float." },
    { word: "lift", hint: "An upward force acting on an object in a fluid." },
    { word: "drag", hint: "Resistance force acting opposite to motion in a fluid." },
    { word: "tension", hint: "A force transmitted through a string or rope." },
    { word: "compression", hint: "A force that squeezes an object." },
    { word: "elasticity", hint: "The ability of an object to return to its original shape." },
    { word: "wave", hint: "A repeating disturbance that transfers energy." },
    { word: "harmonic", hint: "A wave that oscillates at a specific frequency." },
    { word: "doppler", hint: "The effect of frequency change due to motion." },
    { word: "shockwave", hint: "A strong pressure wave moving faster than sound." },
    { word: "sonicboom", hint: "A loud sound caused by an object moving faster than sound." },
    { word: "ultrasound", hint: "High-frequency sound waves used in imaging." },
    { word: "infrared", hint: "Electromagnetic waves with longer wavelengths than visible light." },
    { word: "xray", hint: "High-energy electromagnetic waves used for imaging." },
    { word: "gamma", hint: "The highest-energy electromagnetic waves." }
];
